version: '2'
services:
  matexclude-app:
    image: matexclude
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://matexclude-mysql:3306/matexclude?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8082:8082
  matexclude-mysql:
    extends:
      file: mysql.yml
      service: matexclude-mysql
